name: Go
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1.1.2
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.0.0
    - name: unit-test
      run: go test -mod=vendor -v ./...
